name: Check latest

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check latest version
        id: version
        run: ./check-latest.sh
